version: '2'
services:
  app:
      build: .
      environment:
          REALM: prod
          REDIS_URL: "//redis:6379"
      depends_on:
          - redis
      ports:
          - "8000:8000"

  redis:
      image: redis
